### ISSUE TITLE
OAK-D Pro

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#114]
#### Already released, see [product documentation here](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9098pro.html)

-------

#### 1. Mechanical design.  

The mechanical design of OAK-D is limiting, with the following draw-backs: 
 - Only mounting is a single 1/4-20 tripod mount
 - Lack of 2-screw solution for secure panel mounting (which can result in unintended rotation if additional mechanical design isn't done to prevent this)
 - Bigger than necessary
 - Heavier than necessary

#### 2. Active Illumination

OAK-D was architected for applications where passive depth performs well (and can often outperform active depth; as IR from the sun can be blocked by the optics when purely-passive disparity depth is used).  

There are many applications however where active depth is absolutely necessary (operation in no light, with big/blank surfaces, etc.).  And there are many OAK-D customers who would like to use the power of OAK-D in these scenarios where purely-passive depth is prohibitive.  

### Move to the `how`:

 - Add a VESA-spec (7.5cm, M4) set of mounting holes to the back of the enclosure, moving the tripod-mount to the bottom.
 - Retool the image sensors and layout to minimize size and weight while improving thermal performance.
 - Add IR laser dot projection (for no-light depth) and IR LED blanket illumination (for no-light computer vision/perception).
 
 Architect the IR laser and IR LED such that all these modes of operation are supported:

The idea is that they'd be used in one of these permutations:

1. IR laser on for all frames
2. IR LED on for all frames
3. IR laser on for even frames, odd frames no illumination (ambient light)
4. IR LED on for even frames, odd frames no illumination (ambient light)
5. IR laser on for even frames, IR LED on for odd frames
6. IR laser and IR LED on for all frames
7. IR laser and IR LED both off for all frames.

It is likely that mode 1 and 5 will be used the most.  But enabling all the permutations above allow maximum flexibility for adapting illumination to an application (including dynamically).  For example Mode 6 will likely rarely be used, but there are certain cases where having both on may be beneficial. 

### Move to the `what`:

Same image sensors and FOV of OAK-D:
- 2x OV9282 (but IR capable)
- 1x IMX378 fixed-focus
- IR laser dot projector
- IR LED
- Small, easier-to-integrate form-factor like below:
![image](https://user-images.githubusercontent.com/32992551/130335451-f2b932d9-9cb6-44ce-927b-3dba36443bb5.png)
![image](https://user-images.githubusercontent.com/32992551/130335453-256f0c3d-bdcb-4c7c-a79c-5ba6db383183.png)

**Comment by Luxonis-Brandon** [comment]
It's here!  And everything works!
![image](https://user-images.githubusercontent.com/32992551/134397602-ebaa8e6d-db9e-4083-95df-0c9ffcc9e831.png)

**Comment by Luxonis-Brandon** [comment]
BELAGO 1.1: [https://ams.com/belago1.1](https://ams.com/belago1.1)

**Comment by avenarobotics** [comment]
Good choice, i tested it few days ago. Looks good.

**Comment by Luxonis-Brandon** [comment]
> Are you designing OAK-D-PRO hardware to deal with peer sensor interference?

Not explicitly.  That said our multi-camera sync is likely accurate enough that an inherited solution already exists and is likely to be sufficient.  At least for active disparity depth - so for OAK-D-Pro.  (Not sure on ToF.  Will need investigation.)

**Comment by diablodale** [comment]
Like https://www.cs.unc.edu/~maimone/media/kinect_VR_2012.pdf

**Comment by michaelkr** [comment]
@diablodale  I'm interested in how that might occur. With structured light or Lidar, yes of course, but overlapping illumination patters in stereo systems are expected to *improve* the resulting depth map, not degrade it. Interested, Michael

**Comment by michaelkr** [comment]
I don't believe those things should matter - stereo-based systems stereo don't need to associate projected patterns with an individual sensor (or any sensor at all, for that matter). The dots are there just to provide texture in the scene in situations where there is none (uniformly-painted walls, for eg), so that stereo matching can occur - but it does not matter from what source. For example, the Intel RealSense stereo cameras (*not* their structured light cameras) are of a similar design and can overlap without issue.

**Comment by nalzok** [comment]
Is there any chance you can center the laser dot projector on the device? Maybe it's just me, but the asymmetric design doesn't seem super elegant. It would be awesome if you could move the projector right below the color camera!

**Comment by doisyg** [comment]
> I don't believe those things should matter - stereo-based systems stereo don't need to associate projected patterns with an individual sensor (or any sensor at all, for that matter). The dots are there just to provide texture in the scene in situations where there is none (uniformly-painted walls, for eg), so that stereo matching can occur - but it does not matter from what source. For example, the Intel RealSense stereo cameras (_not_ their structured light cameras) are of a similar design and can overlap without issue.

Same observation here , we have been using d435s with overlapping FoV for a while with no issues. To my understanding, as long as the patterns are sharp enough, they are adding more textures for the stereo matching. The only way I see it could have an adverse effect is if you have enough patterns projected to saturate the camera (or to re-use the spray analogy, if you have painted completely and uniformly your wall).

**Comment by avenarobotics** [comment]
What stereo matching algorithm You want to use? What limitation it has? Resolution/disparity range/fps ?

**Comment by Luxonis-Brandon** [comment]
Sorry @KySmith1 I missed this.  Likely February 2022 but just a guess right now.

**Comment by gluxkind-k** [comment]
> It's here! And everything works!
> ![image](https://user-images.githubusercontent.com/32992551/134397602-ebaa8e6d-db9e-4083-95df-0c9ffcc9e831.png)

What is the width dimension of this (including the enclosure and without the enclosure)?

**Comment by Luxonis-Brandon** [comment]
Great question.  I don't immediately have these - so I'll ask the team for specifics and to share them here.

**Comment by simondemeule** [comment]
Hi! Just a curious onlooker chiming in. 

The hardware you are developing is awesome, and there is one specific use case I could see it absolutely shredding: eye-tracking. With the right software, this could possibly match the performance of multi-thousand-dollar research-grade eye-tracking devices. 

Classical algorithms for eye-tracking rely on point light sources creating sharp reflections on the eye; through some geometric formulation of the problem, it is possible to recover eye position very accurately. Depending on the number of cameras and number of light sources, the problem becomes either under or over-constrained, and can be solved with different degrees of accuracy, with or without assumptions about head position. There are also likely some more modern machine-learning based approaches to this problem, but fundamentally, camera and light source count define how the problem is under or over-constrained. Two cameras and one point source is very nice, because it allows accurate inference of head position in 3D space. Most eye-trackers around this price point lack a stereo infrared camera pair; this requires the user to keep their head at a calibrated distance from the eye-tracking device. People need to refrain from moving around naturally for things to work properly, which isn't great for something like interactive art installations.

In all cases, having high resolution and framerate is important for good eye-tracking. It seems like the stereo pair you have fits the bill nicely — the resolution is likely high enough to get a decent patch of pixels on the eyes, and the framerate is great. Another characteristic of higher-end, stereo eye-tracking systems I've noticed is that the spacing between the pairs is often wider than that of the OAK-D. With a bit of maths it would be possible to find an optimal field-of-view and baseline-width for this task, but that would imply making a completely new hardware design, which maybe is a bit much to ask right now.

However, there is one possibly straightforward optional change that could open a lot of possibilities for this application. If it was possible to produce a variant of this that substitutes the RGB-bayer, IR-filtered IMX378 for its infrared-capable, monochromatic variant, this could open up the door to high-resolution pupillometry in dark lighting conditions — the ability to accurately measure pupil diameter in real-time. This can be a very interesting data point for various applications. Since pupil diameter is  influenced by many psychological factors, but also by the amount of light the eye recieves, this is essentially always done in controlled lighting environments that are often dark — hence it makes sense to use infrared.

And also, just a silly question coming from the aesthetics-obsessed part of me: I assume the white rectangle in the prototype between the IR laser and LED is just the PCB — will the production unit be black?

**Comment by Luxonis-Brandon** [comment]
Thanks @simondemeule !  Yes, the white part goes away in production.  Here's more what final production will look like:

![image](https://user-images.githubusercontent.com/32992551/146840263-236b20e2-c6e2-4f9d-9e18-b097b1297cb4.png)


![image](https://user-images.githubusercontent.com/32992551/146840286-c8d0a2c5-bbd6-4f68-92af-a0d8e66c8409.png)
OAK-D-S2 (passive depth and CV) is the top one, and OAK-D-Pro is the bottom one in the image.

Here's OAK-D-Pro by itself:

![image](https://user-images.githubusercontent.com/32992551/146840361-93a65c0f-69e0-4e2e-bb82-742d5524c2a1.png)

And for doing the change you propose.  Yes, we can likely work with ArduCam to do some custom builds of this type.  It should be relatively straightforward to do so.  

Please feel free to reach out to support@luxonis.com (and link to your comment please if you don't mind) to see about the costs involved here to produce the number of devices you would like here.

Thanks again,
Brandon

**Comment by Luxonis-Brandon** [comment]
![image](https://user-images.githubusercontent.com/32992551/146973728-840bdc5a-4d50-48d7-a7cd-8ebd868f3425.png)

**Comment by sukhrajklair** [comment]
Hi!
Are you planning to build a POE version of this model like the OAK-D-POE?

**Comment by Luxonis-Brandon** [comment]
Yes see here:
https://github.com/luxonis/depthai-hardware/issues/142#issuecomment-998975585

![image](https://user-images.githubusercontent.com/32992551/146975288-98ec89c3-a3c0-4560-86a3-750e32eb752d.png)

**Comment by Luxonis-Brandon** [comment]
We're adding the capability to use USB cables that can fasten to the device.  
![image](https://user-images.githubusercontent.com/32992551/147368345-f8a4d098-90a2-43f6-9770-185cd7d61799.png)

**Comment by simondemeule** [comment]
@Luxonis-Brandon awesome! I'm happy to know we might be able to make this a reality. I'll be in touch.

The production units look nice, this is great industrial design!

**Comment by Luxonis-Brandon** [comment]
Thanks @simondemeule !  Oh and given that you are into machines that make art, check this out done w/ OAK-D-Lite:

![96a121a9b0ca2b35b00a761370d3f971db384766](https://user-images.githubusercontent.com/343936/147397155-7a6f984a-4c58-4578-8e2e-ea1fb49d2872.gif)

https://github.com/keijiro/DepthAITestbed

With OAK-D-Pro I'm sure there will be even more interesting things that can be done.  :-).

**Comment by melsanharawi** [comment]
Hi guys,

Seems to be a wonderful project. Since depth perception should be more accurate with this new version, do you think it could be used for 3d scanning ? It was anounced 3% depth error for the oak-d, do you have an idea of the new depth accuracy in this version ?

Thanks a lot

**Comment by Erol444** [comment]
Hello @melsanharawi , so the below 3% depth error rate is when you have near perfect condition, so great lighting and good texture. When you don't have these, it can be a lot worse (completely random), since disparity matching can't do it's job. Pro having laser dot projector helps with that, and so the error rate is still below 3%.
Thanks, Erik

**Comment by Luxonis-Brandon** [comment]
We also now have ToF for higher accuracy depth for scanning applications.

**Comment by simondemeule** [comment]
@Luxonis-Brandon whoa! That is huge! Is this on a different hardware platform using dedicated ToF image sensors, or are you somehow able to extract accurate-enough timing information from this hardware to create ToF depth maps?

Unrelated to this, I've been a bit slow getting in touch with ArduCam but will do shortly — I would really love to see this project idea come to fruition.

**Comment by michaelkr** [comment]
> We also now have ToF for higher accuracy depth for scanning applications.

Any additional details on this? What sensor is providing this, or the resolution...seems like a large feature add, I'm fascinated!

**Comment by themarpe** [comment]
Hi @simondemeule and @michaelkr 
Check the following: https://docs.luxonis.com/projects/hardware/en/latest/#modular-cameras-designs and specifically the ToF: https://docs.luxonis.com/projects/hardware/en/latest/pages/DM0255.html

To answer your question Simon, this is separate ToF sensor, which can be used with our "FFC" lineup. We don't yet have an off the shelf product integrating it, but that might change in the future.

**Comment by BZandi** [comment]
> Hi! Just a curious onlooker chiming in. 
> 
> 
> 
> The hardware you are developing is awesome, and there is one specific use case I could see it absolutely shredding: eye-tracking. With the right software, this could possibly match the performance of multi-thousand-dollar research-grade eye-tracking devices. 
> 
> 
> 
> Classical algorithms for eye-tracking rely on point light sources creating sharp reflections on the eye; through some geometric formulation of the problem, it is possible to recover eye position very accurately. Depending on the number of cameras and number of light sources, the problem becomes either under or over-constrained, and can be solved with different degrees of accuracy, with or without assumptions about head position. There are also likely some more modern machine-learning based approaches to this problem, but fundamentally, camera and light source count define how the problem is under or over-constrained. Two cameras and one point source is very nice, because it allows accurate inference of head position in 3D space. Most eye-trackers around this price point lack a stereo infrared camera pair; this requires the user to keep their head at a calibrated distance from the eye-tracking device. People need to refrain from moving around naturally for things to work properly, which isn't great for something like interactive art installations.
> 
> 
> 
> In all cases, having high resolution and framerate is important for good eye-tracking. It seems like the stereo pair you have fits the bill nicely — the resolution is likely high enough to get a decent patch of pixels on the eyes, and the framerate is great. Another characteristic of higher-end, stereo eye-tracking systems I've noticed is that the spacing between the pairs is often wider than that of the OAK-D. With a bit of maths it would be possible to find an optimal field-of-view and baseline-width for this task, but that would imply making a completely new hardware design, which maybe is a bit much to ask right now.
> 
> 
> 
> However, there is one possibly straightforward optional change that could open a lot of possibilities for this application. If it was possible to produce a variant of this that substitutes the RGB-bayer, IR-filtered IMX378 for its infrared-capable, monochromatic variant, this could open up the door to high-resolution pupillometry in dark lighting conditions — the ability to accurately measure pupil diameter in real-time. This can be a very interesting data point for various applications. Since pupil diameter is  influenced by many psychological factors, but also by the amount of light the eye recieves, this is essentially always done in controlled lighting environments that are often dark — hence it makes sense to use infrared. The resolution and field of view of the stereo cameras would make it challenging to derive good pupil diameter estimates, however the central camera matches up what is seen in some research-grade setups, given it is placed close enough to the user.
> 

@simondemeule If you like to do high resolution pupillometry with a limited budget, the PupilEXT GitHub repo could be also of interest for you: [https://github.com/openPupil/Open-PupilEXT](https://github.com/openPupil/Open-PupilEXT)

**Comment by Erol444** [comment]
Already released, see [product documentation here](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9098pro.html)
