### ISSUE TITLE
[Documentation] product page should say you recommend the y-adapter

### ISSUE THREAD

**Issue by stuartcrobinson** [luxonis/depthai-hardware#428]
as someone new to the luxonis cameras, it would have been nice if the product page shared that u recommend external power

https://shop.luxonis.com/products/oak-d-lite-1?variant=42583102456031

https://shop.luxonis.com/products/oak-y-adapter
> OAK Y Adapter supplies power to OAK cameras through a USB-C connector. Note that in most cases, the host computer can provide enough current (>1A).

vs

https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/raspberrypi/

> We still recommend externally powering your OAK camera either via barrel jack (on older devices), or with a [Y-adapter](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM6010/#y-adapter). The reason is that there OAK have current spikes (especially when using Video Encoder and running AI inference), which can lead to brownout.

also there's a typo in `reason is that there OAK`

also it would have been nice if the oak-d lite page clarified that it didn't come w/ a cable

**Comment by Erol444** [comment]
Hi @stuartcrobinson ,
1. Most computers have no problem running OAK-D-Lite without external power supply. RPi and other SBC's can have problem due to eFuse, which only allows 1.2A, and it can lead to brownout.
2. Thanks for the typo notice, will fix asap.
3. OAK-D-Lite hardware docs is about hardware, not about the package itself. In shop, it clearly states what's in the package/box: only the camera.
![image](https://github.com/luxonis/depthai-hardware/assets/18037362/d35ed18b-7f9c-4ca4-98b7-b26b59b1fc7d)
