### ISSUE TITLE
DM1097 CM4 HDMI and Keyboard switch problems

### ISSUE THREAD

**Issue by mslavescu** [luxonis/depthai-hardware#46]
I was not able to boot this board 
https://github.com/luxonis/depthai-hardware/tree/master/DM1097_DepthAI_Compute_Module_4

when using I connected to the monitor thorough a 4 port HDMI switch (a few years old model).

I had problems with mouse, left/right click was not working, when was connected through a USB switch, this model:
https://www.amazon.ca/dp/B081V977MX/

Also the Myriad X stopped working after a few seconds when running the automated demo (the NN FPS was 0 and not more detections), and also the whole system will lock (requiring reset) after a minute or two, when the USB switch was connected.

Without the USB switch everything works fine and it is stable, but the no HDMI boot issue is still there.

**Comment by Luxonis-Brandon** [comment]
Thanks.  So I need to find the picture I took of my AMD motherboard being powered parasitically over USB from my USB switch.  Was totally crazy.  It was obvious because my motherboard has a bunch of LEDs.  I unplugged the thing from AC power because I was so confused.  

So the other computer (also AMD) was powering this second AMD machine through the USB switch that both of them were connected to.

On a little device like the BW1097, that only has a 3A supply, it could end up in the same situation where it is trying to power the other devices on the switch.  But unlike my AMD machines, it doesn't have the 10A or 20A required to do so, hence the really strange behavior.
