### ISSUE TITLE
Add OAK-IoT-SoM 

### ISSUE THREAD

**Issue by Luxonis-David** [luxonis/depthai-hardware#97]
#### Already released, see [product documentation here](https://docs.luxonis.com/projects/hardware/en/latest/pages/BW1099EMB.html)

------

Add OAK-IoT-SoM specifications instructions etc.

**Comment by nalzok** [comment]
Could you please also add the Assembly Drawing and BoM for each SoM variant? I just need a rough idea of the onboard components, but I work on a Mac so I don't have access to Altium Designer.

**Comment by Luxonis-David** [comment]
@nalzok unfortunately we can not share the design details about our SoMs, as all hardware design related directly to MyriadX is a proprietary to Luxonis only.

**Comment by nalzok** [comment]
@Luxonis-David I see. Could you tell me what this connector is, and what it is for? I think that is an interface instead of a design detail :)

<img width="320" alt="Screen Shot 2021-10-30 at 09 20 29" src="https://user-images.githubusercontent.com/13443062/139536792-b657f3d4-4225-42ee-9335-18b200a01061.png">

**Comment by Luxonis-David** [comment]
@nalzok yes sure, it is a flat cable connector for JTAG debugging for Myriad X.
This is not exposed to the users and is meant only for internal debugging and development.
Most of the same functionality can be achieved over USB interface though, but we would need to grant you an access in advance,
